const escape = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
export function publicPage(path, config) {
  const contact = escape(config.supportEmail || 'Configure SUPPORT_EMAIL antes de publicar');
  const publisher = escape(config.publisher || 'Publicação ainda não configurada');
  const pages = {
    '/': ['Dia WhatsApp Transcriber', `<p>Leia áudios e organize sua rotina no WhatsApp Web. Extensão independente, sem afiliação ao WhatsApp, Meta ou ao navegador Dia.</p><p>Gratuito: ${config.freeLimit} ações de IA por mês. Trial sem cartão de ${config.trialDays} dias. Um único plano Pro, sem cota mensal de ações para uso pessoal. O preço mensal é exibido na extensão e confirmado no Stripe antes da contratação.</p><p>Nenhuma mensagem é enviada automaticamente em seu nome.</p>`],
    '/privacy': ['Privacidade', `<p>Responsável: ${publisher}. Contato: ${contact}. Versão: 16/09/2026.</p><h2>O que é tratado</h2><p>Seu e-mail verificado, sessão de acesso, status da assinatura e contagens de uso. Áudios e textos escolhidos são enviados ao nosso servidor e ao OpenRouter, que os encaminha ao provedor de IA, somente após consentimento. A transcrição automática é opcional e vem desativada.</p><p>Os resultados e preferências são armazenados no perfil local do navegador. Transcrições e resumos persistidos são cifrados com AES-GCM. A chave fica somente na memória da sessão do navegador, restrita aos contextos confiáveis da extensão. Fechar o navegador descarta a chave; no próximo uso o cache antigo é removido. Reiniciar apenas o service worker preserva o cache. Isso não protege contra alguém com acesso completo ao dispositivo em uso. Apague os dados no popup. No servidor, e-mails, vínculos de cobrança e resultados temporários também são cifrados.</p><h2>Compartilhamento e retenção</h2><p>OpenRouter e seus provedores processam o conteúdo para a IA. Solicitamos roteamento sem coleta para treinamento; retenção operacional e políticas dos provedores continuam aplicáveis. Não prometemos retenção zero por terceiros. O Stripe processa pagamentos, e o Resend entrega códigos de acesso. Não recebemos números completos de cartões.</p><p>Não persistimos arquivos de áudio no servidor. Resultados cifrados de uma solicitação ficam disponíveis por até 10 minutos para repetição segura; a limpeza ocorre a cada minuto. Metadados de uso e eventos de cobrança são mantidos por até 90 dias. Sessões expiram em 30 dias. Códigos expiram em 10 minutos. Um identificador pseudonimizado antifraude pode ser retido por 180 dias após uso do trial ou exclusão. Backups operacionais devem ser eliminados em até 30 dias pelo operador. Registros fiscais do Stripe seguem as obrigações do responsável.</p><h2>Seus controles</h2><p>Você pode revogar o consentimento, apagar dados locais, exportar sua conta e solicitar exclusão pelo popup. A exclusão cancela assinaturas vinculadas antes de remover sua conta. A cópia do áudio no WhatsApp não é alterada. Nunca vendemos comunicações, usamos dados para anúncios ou permitimos leitura humana, salvo consentimento específico, segurança ou obrigação legal.</p><h2>Uso limitado</h2><p>O uso e transferência de informações seguem a Política de Dados do Usuário da Chrome Web Store, incluindo os requisitos de Uso Limitado. Utilizamos dados apenas para funcionalidades solicitadas, segurança e cobrança.</p>`],
    '/terms': ['Termos de uso', `<p>Responsável: ${publisher}. Suporte: ${contact}.</p><p>O gratuito inclui ${config.freeLimit} ações de IA por mês civil em UTC. Transcrever ou resumir consome uma ação bem-sucedida. Falhas não consomem cota. O trial sem cartão dura ${config.trialDays} dias, uma vez por conta elegível, e volta ao gratuito sem cobrança automática.</p><p>O único plano pago é o Pro mensal. O valor e a moeda vigentes aparecem na extensão e no checkout Stripe. Assinar durante o trial inicia cobrança imediatamente; o tempo gratuito restante não é convertido em crédito. A assinatura renova mensalmente até cancelamento no portal, com acesso até o fim do período pago. Falhas de pagamento podem suspender o acesso Pro. Para reembolsos e direitos legais aplicáveis, contate o suporte.</p><p>Sem cota mensal não significa recursos computacionais infinitos: até 24 MB por áudio, dois processamentos simultâneos por conta, ${config.aiRate} solicitações de IA por minuto e disponibilidade do provedor. Não são permitidos revenda de acesso, compartilhamento de contas, scraping em massa, spam ou automações abusivas.</p><p>IA pode errar. Revise resultados antes de utilizá-los. Você deve ter autorização para processar comunicações de terceiros. Não enviamos mensagens em seu nome. Mudanças no WhatsApp Web podem afetar compatibilidade. Produto independente de WhatsApp, Meta e Dia.</p>`],
    '/support': ['Suporte', `<p>Contato: ${contact}.</p><p>Informe versão da extensão e a operação que falhou. Não envie áudios privados, senhas, códigos de acesso ou dados de cartão.</p>`],
    '/billing/return': ['Confira sua assinatura', '<p>Volte ao popup da extensão e clique em Atualizar. O acesso só é liberado após verificação da assinatura no Stripe, não por esta página.</p>'],
    '/billing/cancel': ['Checkout interrompido', '<p>Você pode voltar à extensão e continuar no gratuito ou no trial vigente.</p>'],
  };
  const [title, body] = pages[path] || pages['/'];
  return `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font:17px/1.65 system-ui;max-width:800px;margin:60px auto;padding:0 24px;color:#17332d;background:#f6faf8}h1{font-size:36px}h2{font-size:24px}a{color:#096548}nav{display:flex;gap:20px;flex-wrap:wrap}</style><nav><a href="/">Início</a><a href="/privacy">Privacidade</a><a href="/terms">Termos</a><a href="/support">Suporte</a></nav><main><h1>${title}</h1>${body}</main></html>`;
}
